### PR TITLE
✨ Add `bs.block:spawn_block_particles`

### PR DESCRIPTION
**Pull request by theogiraudet**
# Tasks to do before merging
- [x] I accept to publish my contribution under [MPL v2](http://mozilla.org/MPL/2.0/) License
- [x] My pull request is linked to an existing issue
- [x] I have added my contribution to the [changelog](https://github.com/Gunivers/Bookshelf/blob/master/docs/CHANGELOG.md)
- If my pull request is a new or modify an existing feature:
  - [x] I have documented my contribution (`/docs`)
  - [x] I have added or updated the [header](https://bookshelf.docs.gunivers.net/en/latest/contribute/file-format.html) of the features' root function I contribute
  - [x] I have [tested](https://bookshelf.docs.gunivers.net/en/latest/contribute/debug.html#unit-tests) my contribution

### CODE REVIEW

**Comment by aksiome** [comment]
Everything looks fine, i'm just not convinced by the name. All other spawn functions are summoning a new entity which is not really the case here. Maybe something like `emit_block_particles` would be more appropriate?

**Comment by theogiraudet** [comment]
I agree, but the folder is named "spawn" :/

**Comment by aksiome** [comment]
We can just move the function to an other folder. Also I think we should add a very simple test to just see if the run function is working (in case mojang change the particle command for example)

**Comment by theogiraudet** [comment]
For me, renaming the folder to "produce" would be a better idea. But this is a breaking change…
+1 for the test.

**Comment by aksiome** [comment]
You can rename it it's not breaking change since functions are tagged and the internals are not supposed to be used directly. Im completly fine with this change

**Comment by theogiraudet** [comment]
Oh this is true, my bad. Let's do that, this name is better for new features.

**Comment by theogiraudet** [comment]
@aksiome I let you review the new version.

**Review by aksiome — APPROVED** [review]

**Pull request merged**
