### PR TITLE
Major issue

### PR DESCRIPTION
**Pull request by Leirof**

### CODE REVIEW

**Review by theogiraudet — CHANGES_REQUESTED** [review]
Please, use the new log module instead.

**Comment by Leirof** [comment]
Hmmm, what about no?

**Comment by Leirof** [comment]
Not prioritary, neither my job

**Comment by Leirof** [comment]
Current unit tests will be rewritten with the unit test module ( #106 )
This PR is then out of date even before being merged, so I close it ^^

**Pull request closed without merging**
